### ISSUE TITLE
作業開始・終了報告

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#1]
はじめます

**Comment by kasugamori** [comment]
はじめます

**Comment by kasugamori** [comment]
始めます

**Comment by kasugamori** [comment]
14日の終了時間は寝落ちのため不明です。本日15日11：00〜開始します。

**Comment by kasugamori** [comment]
間違えて閉じてしまいました。

**Comment by uesakaeita** [comment]
そうそう、間違えて閉じちゃうことあるよねー。

本日も頑張って下さい！

**Comment by uesakaeita** [comment]
始めます。
メニュー文章を修正します。

**Comment by uesakaeita** [comment]
7:30　始めます

**Comment by kasugamori** [comment]
8：30〜はじめます。

**Comment by kasugamori** [comment]
開始します。8:30〜

**Comment by uesakaeita** [comment]
はい！

今日のお昼はミーティングでしたね、よろしくお願いします。

**Comment by kasugamori** [comment]
今日は7:50〜9:00作業します。

**Comment by uesakaeita** [comment]
はじめるどん

**Comment by kasugamori** [comment]
はじめていましたどん11:00〜15:00

今日も宜しくお願いします。

**Comment by uesakaeita** [comment]
よろしくお願いします。
今日は12:30～13:30で定例ミーティングですね。
以前アナウンスした、3条件の提示をお願いします。

**Comment by kasugamori** [comment]
10:30〜12:00作業します

**Comment by kasugamori** [comment]
21：00〜作業開始

**Comment by uesakaeita** [comment]
ごめんなさい、栄太、仕事しながら傍らで始めてました。
7:00開始
9:00終了予定
やること
・コンタクトフォームの修正

**Comment by kasugamori** [comment]
9:40〜11:00予定
・石川先生に見てもらうようのハガレンのプロット

**Comment by uesakaeita** [comment]
作業再開します
12:00開始
12:30ミーティング
15:00終了予定

**Comment by kasugamori** [comment]
9:36〜10:00
教会報告用PDF作る

**Comment by uesakaeita** [comment]
間違えて閉じました。失礼しました

**Comment by kasugamori** [comment]
11月24日　18時13分〜
・ハガレンプロットを３割→８割にします

**Comment by kasugamori** [comment]
11.25 14:00~15:00
総務・牧師へのメール。記事下の作成。リンクエー提携申請。

17:46~

ハガレンプロット８割→10割へ

**Comment by uesakaeita** [comment]
始めます
10:30開始
11:30終了予定
バックアップ、テーマの変更

**Comment by kasugamori** [comment]
11月26日　３時間ほど。全体を見たり、管理人プロフなどをいじりました。

11月27日　10:45〜12:００「クリスチャンの方へ」修正
12:00~12:30 ハガレンプロット

**Comment by uesakaeita** [comment]
いまから4話の記事チェックに入ります。

**Comment by uesakaeita** [comment]
始めてました。
16:30開始
17:30終了予定
バックアップ、子テーマ、トップのデザイン変更

**Comment by kasugamori** [comment]
11月29日　０時45〜１時十五バナー作り

**Comment by kasugamori** [comment]
12/1 10:00~11:00
キリスト新聞社、聖書ラノベ新人賞ヘあらすじ応募。作者プロフィールなども掲載。

**Comment by uesakaeita** [comment]
おおっ！
そういえば撒き餌作戦でしたね！

**Comment by uesakaeita** [comment]
キリスト新聞社、聖書ラノベ新人賞ヘあらすじ応募あああ　
作者プロフィール作成。【いつかみ】リンク添付。11:00~クリスマスネタ骨子作り

**Comment by uesakaeita** [comment]
11月の作業、お疲れさまでした！

GitHubの導入が11月15日ころだったと思うので、正確な作業時間の集計は難しいですね。
細切れに作業していた時間もあるでしょうし。

ただ、「GitHubに書いてないことは存在しないと考える」ならば、栄太の投稿した作業時間の合計は42時間でした。

細かい作業や11月1日～15日の期間も含めるならば、80時間ほどでしょうか。

**Comment by uesakaeita** [comment]
かすがさんの作業時間を計算しようとしたのですが、終了時間が書いてなったため、正確な時間は分かりません。

そのため、終了時間が書いてない日は開始時間から4時間作業したとして計算し、（00:00？）と追記しました。

**Comment by kasugamori** [comment]
12/2 15:00~15:45
メルマガ整理
23:00~
いろいろ

**Comment by uesakaeita** [comment]
12月4日ミーティングで話し合いました。

11月15日～30日の作業時間は、
栄太　42時間
かすが　49時間

とします。

お疲れさまでした！

**Comment by uesakaeita** [comment]
作業報告（12月） #63 

へ引き継ぎます。
