### ISSUE TITLE
ディスクリプションについての相談

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#10]
グーグル検索で表示された時のためのディスクリプションを160文字程度で作成しておく必要があります。

**Comment by kasugamori** [comment]
とりあえずこれで行ってみようと思います。
ーーーーーーーーーーー
「日本人だし、家には仏壇と神棚しかないし、だから僕はキリスト教を知らない」ーーー果たしてそれは本当だろうか？マンガ/アニメに見え隠れする聖書のエッセンスが詰まった【いつ神】を読めば、きっと貴方も聖書が身近なモノだと気づくはず。今回は【○○】をテーマに聖書の話を拾い上げていく。
ーーーーーーーーーーー
SNSなどの実際のシェアされ方などを観察して、改変することも考えています。

**Comment by uesakaeita** [comment]
了解！
いいと思います😊
