### ISSUE TITLE
マンガBANG!　⭐️⭐️2月28日に要確認

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#100]
【導入マンガ】
ヒカルの碁・るろうに剣心

※なぜか案件がアップルストアしかないっぽいのでアンドロイドでどう表示されるかチェックしたい

**Comment by uesakaeita** [comment]
アンドロイドのタブレット、どうぞ使ってください。

**Comment by uesakaeita** [comment]
リンク張り替えの時に、私も同席します。
教えて下しさい。

よろしくお願いします。

**Comment by uesakaeita** [comment]
2018年5月21日、ミーティングで話し合いました。
アフィリエイト案件は終了し、アプリとしての特徴も親和性が低いと判断したので、以降も紹介しません。
クローズします。
