### ISSUE TITLE
紙の聖書希望の人への対応

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#11]
選択肢3つほど考えています。

1.私たちが対応して、ギデオン聖書を郵送していく（ユーザーには送料のみ負担してもらう）
2.ギデオン協会の人（身近な人でいうとUさん）に依頼する
3.聖書郵送はせず、信頼できる「聖書通信講座」を勧める（ただし、「いつ神」からのオファーの数は知ることができないと、サイト運営が難しくなるのでやり方は考えなくては）
→「難しくなる」とは、フィオードバックがないと精神的に辛くなるということ/数が分からないと改善などが手探りになってしまうこと　が起きると思われるから。（メルマガを運営した時の所感より）

**Comment by kasugamori** [comment]
信頼できる聖書通信講座があれば必要ない可能性があります。

**Comment by uesakaeita** [comment]
1.と2.に関しては、サイトがリリースできたら、ギデオンに関してUさんに聞いてみましょう。日程未定ですが、最短だと11月29日ですね。

3.はまずは候補を出して考えてたいと思います。
どこか候補はありますか？

**Comment by uesakaeita** [comment]
11月29日、ギデオンのUさんに確認しました。
つぎは、
３．のFEBCの聖書（400円）の発送依頼に入ります。

**Comment by uesakaeita** [comment]
FEBCに発送依頼をし、すぐに届きました。

上記の選択肢３つの補足

１、ギデオンから郵送してもらう→不可とわかりました（http://www.gideons-jp.org/faq）

２、知り合いのギデオン会員に依頼する→１万部とかじゃないならいいよとのこと。新改訳。

３、FEBC→すぐ届くが、送るまでに手間がかかる。めんどくさいし、知らないところに手紙を出すのは少しハードルがある。若い人は特にあると思う。新約のみ、小さい。新共同訳。FEBC添付資料は、いいのもあった。


お問い合わせのない現状は、２と３の併記でいいと思います。
「FEBCというところで４００円で送ってもらえるよ、こちらにお問い合わせもらえたら【いつかみ】からも送料のみで対応できるよ。」といったニュアンス。

お問い合わせが増えたら考え直しましょう。

いかがでしょうか。

大丈夫であれば、コメントとcloseをお願いします。

**Comment by uesakaeita** [comment]
##2月5日のミーティング

ユーザーのストレスを減らすために、選択肢を2つ出すのではなく、1つに絞ることにします。

FEBCの聖書郵送を紹介をしましょう。

聖書希望のユーザーが、私たちの個人ブログに対して、個人住所を伝えることがハードルになるのではと思ったためです。

とりあえず決定とし、closeします。
