### ISSUE TITLE
第8話　CCさくら

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#110]

**Comment by kasugamori** [comment]
![img_3265](https://user-images.githubusercontent.com/33079296/35479241-d8642f8e-0435-11e8-8262-323039c1050d.JPG)

**Comment by kasugamori** [comment]
NくんとNさんにインタビュー予定

**Comment by uesakaeita** [comment]
先日のNくんへのインタビュー、いろいろ聞けてとても参考になりました。
こういう機会もいいですね。
今日のインタビューも楽しみですね。

**Comment by kasugamori** [comment]
インタビューを経て練り直した新しい骨子です。
![img_3576](https://user-images.githubusercontent.com/33079296/36139961-e89e8c1e-10e2-11e8-8192-8d09d1f4c6d3.JPG)

**Comment by uesakaeita** [comment]
WordPressの下書きに落とし、キャラ画像を挿入しました。

いくつか相談・質問があります。

①パーマリンクは何にしますか？
cardcaptor-sakura
か
sakura

②カテゴリーは、恋愛とファンタジーでいいでしょうか？

③アイキャッチは、私が仮で作ってもいいでしょうか？

④あらすじの引用元のリンクを教えてください

⑤エステル記の説明のボックスは、仮で囲います。デザインアイデアがあったら教えてください。

⑦エステル記、書簡ではないのでは？と思ったので、2箇所ほど、書簡と記入があったところを修正しました。
間違いでしたらごめんなさい。

⑧あおいのセリフ「いいキャラすぎて怖いんです。知世はさくらのこと好きなんですよ。好きな人のそばにいてその人が幸せなのを喜べるのって、人間味がなさすぎません？」
の補足説明を追加した方がいいのでは、と思いました。私の方で少し追加しようと思うので、変だったら教えてください。

**Comment by kasugamori** [comment]
①パーマリンクは何にしますか？
→ccsakura   か　　cc-sakura

がいいかと思います。

②カテゴリーは、恋愛とファンタジーでいいでしょうか？
→いいと思います…が、

ジャンヌもまどマギもあるので「魔法少女」を作ってもいいのかもしれませんね。どう思います？


③アイキャッチは、私が仮で作ってもいいでしょうか？
→お願いします。ジャンヌのアイキャッチもお願いします。

（アイキャッチは、今の形式でいく間はすべては栄太さんに作ってほしいです。私は作り方がわかりませんので。）

④あらすじの引用元のリンクを教えてください
→オリジナルです。

⑤エステル記の説明のボックスは、仮で囲います。デザインアイデアがあったら教えてください。
→見て決めます。

⑦エステル記、書簡ではないのでは？と思ったので、2箇所ほど、書簡と記入があったところを修正しました。
間違いでしたらごめんなさい。

→見てまた判断します。

⑧あおいのセリフ「いいキャラすぎて怖いんです。知世はさくらのこと好きなんですよ。好きな人のそばにいてその人が幸せなのを喜べるのって、人間味がなさすぎません？」
の補足説明を追加した方がいいのでは、と思いました。私の方で少し追加しようと思うので、変だったら教えてください。

→口頭で伝えた通りです。

**Comment by uesakaeita** [comment]
3日前、記事発行することができました。
ありがとうございます！

クローズして大丈夫であれば、お願いします。
