### ISSUE TITLE
全体のストーリー構成について

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#112]
キャラクターたちの像も見えてきたので、ここでいったん「全体の起承転結」みたいなものを2人で考えたいと思います。

**Comment by uesakaeita** [comment]
## 2月9日ミーティング

参考文献

- ヒーローズジャーニー　神話の法則

- セーブザキャット

- （物語の法則）

**Comment by uesakaeita** [comment]
3.5時間ほどのミーティング、お疲れ様でした。

メインのあおいストーリーは、セーブザキャットのフレームワークで考え

水面下のたくみストーリーはヒーローズジャーニーのフレームワークで考え

それぞれのストーリーの要所をふせん書き出しをしました。

写真を添付しておきます。

**Comment by uesakaeita** [comment]
![da49d24b-c512-430e-9b82-894d3d6c0f71](https://user-images.githubusercontent.com/33074227/36017418-fecc71b6-0dba-11e8-9c3b-7eaeb77fe143.jpeg)
![dd6c7be5-8360-44ab-868c-dc7242023486](https://user-images.githubusercontent.com/33074227/36017419-fefb95b8-0dba-11e8-85a8-85effc46bbbb.jpeg)
![101dd462-cf93-4138-8171-db7713828b4d](https://user-images.githubusercontent.com/33074227/36017420-ff2db32c-0dba-11e8-99bd-701de081db40.jpeg)
![a6bbcfb7-0474-4aa5-9d9b-0fa55e72fe58](https://user-images.githubusercontent.com/33074227/36017421-ff55f634-0dba-11e8-9695-bef6ab4f5ed4.jpeg)
![5e2fbae3-f3cd-4392-b31e-087bdfc39bfd](https://user-images.githubusercontent.com/33074227/36017423-ff8d6a88-0dba-11e8-9c4b-19db99deb24c.jpeg)
![3f2adb00-068b-4975-9f49-1dbac28b1a5b](https://user-images.githubusercontent.com/33074227/36017424-ffc5e728-0dba-11e8-9618-8afbd87dd9e7.jpeg)

**Comment by uesakaeita** [comment]
脱線して作った「とある町マップ」
も添付しておきます。

**Comment by uesakaeita** [comment]
![aec7397e-3cab-43a0-88ca-579609ef3ffe](https://user-images.githubusercontent.com/33074227/36017525-69c6106c-0dbb-11e8-9556-acfe23620ea0.jpeg)
