### ISSUE TITLE
いのちのことば社へのバナー広告のお問い合わせ

### ISSUE THREAD

**Issue by uesakaeita** [lampmate/itukami#114]
2月4日、かすがさんが
いのちのことば社のHPでの広告欄について、口頭で質問していただいた件ですが、

実際にいのちのことば社へお問い合わせをしますか？

**Comment by kasugamori** [comment]
条件が満ちたときに再検討を考えています。
【条件】
・PV数の伸び悩み
・フォロワー数の伸び悩み

【考慮したい条件】
・「いのちのことば社」ウェブサイトに来るユーザー数（日に何軒くらい訪問があるのか）
・「いのちのことば社」ウェブサイトに来るユーザー特性（年齢層や離脱している条件など）

ーーー
ひとまずSNS運営やSEO対策、ドメインパワーアップ、記事数増やしをしてみて、それらに行き詰まりを感じたときに再検討だと思っています。いかがでしょうか。

**Comment by uesakaeita** [comment]
承知しました！
closeします。
