### ISSUE TITLE
新キャラのデザイン

### ISSUE THREAD

**Issue by uesakaeita** [lampmate/itukami#123]
かすがさん作成中

あおい姉→あかねさん完成

あおい母→作成中

教会信徒のマンガ好き少年→創くん完成

**Comment by kasugamori** [comment]
【完成】

あかね
みどり
創

ーーーーー
【作成中】
創ママ

**Comment by uesakaeita** [comment]
全体像の再構成も終わり、
必要なキャラは完成している様に思いますが、いかがでしょうか。
大丈夫でしたらクローズをお願いします。
