### ISSUE TITLE
新キャラ「創くん」について

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#124]
新キャラ「クリスチャンホームの創（そう）くん」のキャラクター性/好きなマンガを考えています。

・葵→少女マンガ系等（一応）
・拓海→王道少年マンガ（一応）

という設定なので、創くんは栄太さんが好きな系統の漫画と、プラスして「セカイ系」を主軸に据えるのはどうかなと思いますがいかがでしょう？
![kyoukainoseinen](https://user-images.githubusercontent.com/33079296/36087444-c6c20a58-1015-11e8-9453-8c46acb28f07.png)

葵と対比させるために過保護なクリスチャンママに過干渉されているという設定を考えていることはお話しした通りですが、クリスチャンママがいかにも嫌いそうなマンガが好きだと整合性が取れるかなと思っています。

それでOKの場合、そろそろ登場させたいので取り扱い作品を決めたいと思っています。現在ピックアップされている「栄太さんが中心予定の作品ORセカイ系」のタイトルはこんなカンジです。

・灰羽連盟
・銀河英雄伝説
・ひぐらし
・ARIA
・サクラダリセット
・メイドインアビス
・まど☆まぎ
・エヴァ
・ぼくらの
・進撃の巨人

**Comment by uesakaeita** [comment]
創くんのマンガの方向性は、私が好きなマンガor世界系、いいと思います！

上記マンガリストの修正をお願いしたい箇所がありまして、「ぼくらの」は、私はちゃんと見てないので全然かけないです。かすがさんが好きなんだと思っていました。二人とも興味がなければ、リスト一覧から削除しましょう。

創くんのイラストもありがとうございます！
イラストに関しては私に口出しする権限はそんなにないと思っているのですが…頭のハイライトがどうも気になってしまいます。９０inch 程度のサイズにして、違和感がなければいいと思いますが、大き目のサイズで見ると、私はどうしても気になってしまいます…慣れるのかな。

**Comment by kasugamori** [comment]
「ぼくらの」はセカイ系です。
創くんのイラストは修正します。

**Comment by uesakaeita** [comment]
## 2月16日ミーティングにて

勘違いしていました。了解しました。よろしくお願いします。

11話にて、創くんがメインの話しにする予定。
題材マンガは、まどかマギカ？（仮）

**Comment by uesakaeita** [comment]
全体の構成を縮めて再構築するので、創くんストーリーはそれほど数は増えなさそうですね。

クローズします。
