### ISSUE TITLE
第6話　神風怪盗ジャンヌ

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#127]
「ジャンヌのキリスト教観は変なのか？」について葵が質問して石本伝道師が語っていくスタイル。
![img_3669](https://user-images.githubusercontent.com/33079296/36467204-0f4346b8-1721-11e8-8f0a-69b61a8e8cda.jpg)

**Comment by uesakaeita** [comment]
記事発行にまでたどり着きました。ありがとうございます！

クローズしても大丈夫でしたら、お願いします。
