### ISSUE TITLE
Today’s聖書ポイント（仮）

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#137]
Dさんがアドバイスくださったように、「結局なにがいいたいのかがよくわからなくなっている」という課題があります。毎話の終わり頃に聖書箇所を２．３点にまとめて挿入したらいいかなと思うのですがいかがでしょう？その場合のキャッチフレーズを考えたいと思います。

**Comment by uesakaeita** [comment]
わかりました。
キャッチフレーズ考えましょう。


要点

まとめ

今日のポイント

あおいのチェックポイント

わかった

結論

チェック

明日使える○○

今日のトリビア（古）

本日のレシピ

**Comment by kasugamori** [comment]
【石本的聖書ポイント】に決定。
h2ごとに挿入するか、各話のエピローグ前に挿入するか一度やってみて私がバランスを見て決めることにしました。

**Comment by kasugamori** [comment]
【ラビー的聖書ポイント】に変更、ラビーちゃんを天の声として登場させる。

**Comment by kasugamori** [comment]
・第5話ヒカルの碁の聖書ポイント書く
