### ISSUE TITLE
プレゼン外出について

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#141]
◆第一回プレゼン外出　5/29 インデジタス　御茶ノ水
・やること　　１分動画かスライドショーの作成
・【いつかみ】を見せていい状態にしておく（内容、デザインともに）
・申し込み

**Comment by uesakaeita** [comment]
パワポ資料作成メモ

http://thepopp.com/how-big-should-text-be-in-powerpoint/


http://thepopp.com/recommended-fonts-for-powerpoint/

https://biz-que.com/cool-presentation-doc/

**Comment by kasugamori** [comment]
報告記事を書きました
http://kasuga-1221.hatenablog.com/entry/indigitous

**Comment by kasugamori** [comment]
![img_1794](https://user-images.githubusercontent.com/33079296/40901018-3f85caba-6809-11e8-92c3-ac0a4c23e4fa.jpg)
![img_1796](https://user-images.githubusercontent.com/33079296/40901019-3fadb02a-6809-11e8-973c-5983fa1a7e84.jpg)
![fullsizerender 4](https://user-images.githubusercontent.com/33079296/40901036-5a5792c4-6809-11e8-99cb-d21028e1ac17.jpg)
![fullsizerender 7](https://user-images.githubusercontent.com/33079296/40901037-5a7f76a4-6809-11e8-9e3c-3aa0e71e0674.jpg)
![fullsizerender 8](https://user-images.githubusercontent.com/33079296/40901038-5aae4718-6809-11e8-8819-90108089e2a8.jpg)
