### ISSUE TITLE
YouVersionについて

### ISSUE THREAD

**Issue by uesakaeita** [lampmate/itukami#145]
毎記事の最下部に紹介しているYouVersionのアイコン画像を修正しました。
データはストレージにアップしてあります。

YouVersionの本家サイトの提供資料からいただきましたが、元画像の下部をカットしてあります。
http://blog.youversion.com/churches/

**Comment by uesakaeita** [comment]
修正前の画像
![youversion](https://user-images.githubusercontent.com/33074227/39665202-2d343c70-50cb-11e8-885f-92e6c0f9fa7a.png)

**Comment by uesakaeita** [comment]
YouVersion本家の提供資料の元画像
http://blog.youversion.com/churches/

![youversion_honkekara-motogazou-1920x1080](https://user-images.githubusercontent.com/33074227/39665212-46e1a090-50cb-11e8-9287-312bc6c61138.jpg)

**Comment by uesakaeita** [comment]
下部をカットした修正後の画像
フィルターでもうちょっとシャープにしておけばよかった。。。背景にある多言語文字が見えなくて白背景に見えてしまいますね。。。ちょっともったいないかな。

![youversion-1-700x490](https://user-images.githubusercontent.com/33074227/39665217-5c23b114-50cb-11e8-9532-792ded459157.png)

**Comment by uesakaeita** [comment]
日本語を書き重ねたバージョン
![youversion-ja-700x490](https://user-images.githubusercontent.com/33074227/39673284-48ea6aa8-5174-11e8-8288-55cec3ae639c.png)

**Comment by uesakaeita** [comment]
「watch/観れる」の文面の確認としてムービーを観てみましたが、
それほど全面に押し出す必要はないと判断しました。

5月6日、話し合った結果、
本家youversionに対してリスペクトの思いはありますが、
デフォルトの提供資料ではいつかみの趣旨として届けたい、ダウンロードしてもらいたい人への訴求力が低いと思われるため、画像を作り直そうという話になりました。

**Comment by kasugamori** [comment]
ためしに
