### ISSUE TITLE
KGI/KPIの設定

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#15]
とりあえずKGI（最終的な目標）を決めて、そこからKPI（最終的な目標（ KGI）を達成するための、過程を計測する中間指標）を決めて、それぞれ見直す期間も決めておく必要があると思います。次回のミーティングで決めていきたいです。今のところオーガニック検索狙いではありませんので、私のSNSのフォロワー数（フォロワー数は700未満だけど、よく絡んでいたのは10名以内。絡んでない人は全員アンチになるくらいに考えてもいいと思う。）や、個人ブログのPV数（1日300PVくらい。いつ神との親和性は高い内容）、メルマガ読者数などからある程度の数字を出す作業をしておきます。

**Comment by kasugamori** [comment]
上坂かすがの希望覚書き。
・「いつ神」は、“30人いたら1人に響くようなものを作る”というコンセプトで作る
・SEO対策は後回しで、ひとまず「回遊率」や「リターンユーザー」を大事にする。
・1Pの滞在時間1分50秒くらいであれば良いのではないかという感覚
・クリスチャンの創作家2人と、クリスチャンでない創作家2人に読んでもらって感想をもらう。アンケートは別データで添付。

**Comment by kasugamori** [comment]
最初の5名用アンケート

ーーーーーーーーーーー

【いつ神】を読んでもらって抱いた感想を教えてください。
 
 
・面白いと感じましたか？
→「思う」場合。内容？コンセプト？
 
 
 
・面白くないと感じた場合
→「どうしたら面白くなると思いますか？」
 
 
 
・難しいと感じましたか？
 
　　→具体的な箇所があれば。
 
 
 
・自分も書いてみたいと思いましたか？
 
　→「思う」場合は会話形式でのストーリーorコラムか確認。その理由も。
 
 
 
 
　→「思わない」場合は「マンガと聖書箇所の提出だけなら？」「リンクなら？」の確認。またその理由。

**Comment by uesakaeita** [comment]
了解しました。
次回ミーティングが楽しみです！

**Comment by kasugamori** [comment]
11/17ミーティング決定事項
「いつ神」の目標2018.11.30までに3万pv/SNSフォロワー3000人(Twitter＋フェイスブックページ)どちらか達成できればよし。
・ペルソナb→メアドでつながること←商材つくる
・ペルソナc→メアドでつながること←商材つくる(脱依存の実績使ってよし)

**Comment by kasugamori** [comment]
KGIについて訂正です。統計を調べて計算し直しました。

●ターゲット→日本人/13〜29歳/クリスチャン以外/インターネットを利用する

という条件のもと数字を出すと、「616,673名」でした。約60万名です。
