### ISSUE TITLE
スペシャルサンクスについて

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#153]
2018/6/1MTG

https://itukami.lampmate.jp/thanks

【スペシャルサンクス】→アイデアの寄稿、感想を伝えてくれたなどの方々。
・軽い紹介
・相手の紹介したいネット媒体／SNSのリンク。（２本まで。amaznほしいものリスト除く）
・通っている教会（許可制）

**Comment by kasugamori** [comment]
【スペシャルサンクス】の主旨
・「クリスチャン全体」の益となる活動をしたい！

・「クリスチャンの横つながりを強める手助けの一つとなりたい」という思いから
・そのために、個人で活動している人たちも応援したい
・【いつかみ】そのものの趣旨に興味を持ってもらえなくても、「クリスチャンの横つながりを強める活動をしたい」に共感してくれる人は多いと思うので
・次のステップ（教会ガイドか、キュレーションメディア）についての理解を促進するため

ーーーーーーーー

**Comment by uesakaeita** [comment]
わかりました。

さっそくN.Nさんに連絡してみました。
土日で時間があるときに電話できないか打診しましたので、電話で掲載許可の有無を確認したいと思います。

**Comment by kasugamori** [comment]
【確認中の下書きコピペー確認次第本ページに投稿します】
<p>&nbsp;</p>
<p>ーーーー（以下、確認中の方々です）ーーーー</p>
<h4><img class=" wp-image-3089" src="https://itukami.lampmate.jp/wp-content/uploads/2018/06/Lampfire150-202.png" alt="" width="30" height="40" />M.M（S.K）さま（仮）</h4>
<p>貴重なお時間をさいてくださり、感想をお伝えくださったほか「第　話　夏目友人帳」のアイデアをくださり、励ましをくださいました。</p>
<p><span style="color: #cc99ff;">※ここに紹介したいURLとその説明を入れる</span></p>
<p>[box class="box26" title="通っている教会"] ◯◯県　◯◯教会[/box]</p>
<h4><img class=" wp-image-3089" src="https://itukami.lampmate.jp/wp-content/uploads/2018/06/Lampfire150-202.png" alt="" width="30" height="40" /></h4>
<p><strong>T.Lさま（仮）</strong></p>
<p>感想をくださいましたほか、不備部分の報告などをくださりおおきな励ましとサポートをしてくださいました。</p>
<p><span style="color: #cc99ff;">※ここに紹介したいURLとその説明を入れる</span></p>
<p>[box class="box26" title="通っている教会"] ◯◯県　◯◯教会[/box]</p>
<h4><img class=" wp-image-3089" src="https://itukami.lampmate.jp/wp-content/uploads/2018/06/Lampfire150-202.png" alt="" width="30" height="40" /></h4>
<p><strong>T.Dさま（仮）</strong></p>
<p>タイトルの相談に乗ってくださいましたほか、感想をくださり大きな励ましをくださいました。</p>
<p><span style="color: #cc99ff;">※ここに紹介したいURLとその説明を入れる</span></p>
<p>[box class="box26" title="通っている教会"] ◯◯県　◯◯教会[/box]</p>
<h4><img class=" wp-image-3089" src="https://itukami.lampmate.jp/wp-content/uploads/2018/06/Lampfire150-202.png" alt="" width="30" height="40" /></h4>
<p><strong>S.O（K.Y）さま</strong></p>
<p>英語翻訳のお手伝いをしてくださいました。学生として勉強しながら、宣教師を志してその勉強中でもあります。ご支援お願いいたします。</p>
<p><span style="color: #cc99ff;">※ここに紹介したいURLとその説明を入れる</span></p>
<p>[box class="box26" title="通っている教会"] ◯◯県　◯◯教会[/box]</p>
<p>&nbsp;</p>
<h4><img class=" wp-image-3089" src="https://itukami.lampmate.jp/wp-content/uploads/2018/06/Lampfire150-202.png" alt="" width="30" height="40" /></h4>
<p><strong>N.Nさま</strong></p>
<p>「<a href="https://itukami.lampmate.jp/cc-sakura">第8話「カードキャプターさくら」さくらの可愛さはエステル？知世が怖いってどういうこと？</a>」制作にあたって、貴重なご意見をいただきました。</p>
<p><span style="color: #cc99ff;">※ここに紹介したいURLとその説明を入れる</span></p>
<p>&nbsp;</p>
<p>&nbsp;</p>

**Comment by uesakaeita** [comment]
2018年6月4日、ミーティングにて話し合いました
（6月3日の事案にケース④があったため、整理することになりました）


# ウェブ媒体を持っている人にいつかみのリンクを張ってもらえないか、打診する時の統一ルール

## ケース①：いつかみを見たことがあり、好感をもっている。ウェブ媒体を持っている人の場合

step1：「応援していただけて嬉しいです。いつかみのスペシャルサンクスのページで〇〇さんのブログを紹介させてもらってもいいですか？スペシャルサンクスのページはいまこんな感じです」と見せて伝える。
step2：OKであれば、下書きを書きリンクを送り、OKであれば発行。「もし可能であればいつかみのリンクを張ってもらえたら嬉しいです。リンクを貼ったら教えてください」と伝える。
step3：半年たって、特に変動がなければ、他のスペシャルサンクスとの兼ね合いをみてアーカイブにするか判断する。


## ケース②：いつかみを見たことがあり、好感を持っているか不明。ウェブ媒体を持っているか不明の場合
好感を持っているかを判断する。
判断できない場合は、関心なしと判断し、それ以上説明しない。
場合によってはリンクをラインで送るまで。

## ケース③：いつかみを見たことがあり、好感を持っていない場合
そもそも話題にしない。主旨の説明などもしない。


## ケース④：いつかみを見たことがなく、ウェブ媒体を持っている人の場合
近況報告の中でいつかみが話題になれば、その時の感触で好感を持っているかを判断する。
判断できない場合は心関心なしと判断し、それ以上説明しない。
場合によってはリンクをラインで送るまで。
