### ISSUE TITLE
終了します

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#159]
もういつかみはやめましょう。栄太さんはの実験が気に食わなかったのですよね。もうやめましょう。十分だと思います。

**Comment by uesakaeita** [comment]
話しあう必要がありますね。
ミーティングの時間をとりましょう。

6月22日、金曜日はどうですか？

**Comment by kasugamori** [comment]
必要ありません。

**Comment by kasugamori** [comment]
ミーティングするとしたらそれは遅すぎます

**Comment by uesakaeita** [comment]
すみません、次の19日月曜日は定例ミーティングの日ですが、
私が忙しいためミーティングできません。
そのため22日金曜日にしたいと思いました。

**Comment by uesakaeita** [comment]
# 2018年6月22日ミーティングにて
いつかみのゴールについて話し合いました。

## 決まったこと

- 当初の予定の11月30日締め切りは、条件により分岐する。

- もし11月30日になっても24話完結しなかった場合は、閲覧者の声によって継続するか判断する。SNS、お問い合わせからのメール、口頭、で継続してほしいという声が10件あれば、1か月延長する。

- 11月30日までに、企業からの番外編案件があれば、そちらを優先させるため、11月30日の締め切りを延期させる。

- 24話が11月30日に終わった場合、または11月30日より早く終わった場合は、いつかみ24話を商品サンプルとしてキリスト教関連企業・団体へ番外編を売り込めるよう商品企画作成にシフトする。商品売り込み期間をいつまでにするかは、完結後のミーティングで決める。

- いつかみ完結後、海外からの支援を具体的に現実的に収益化に結びつけるための施策を考える。


## 確認したこと

- 栄太もかすがも、いつかみを切り口に収益化をしたいと思っている。

- 両者とも、いつかみには宣教としての価値があると思って作っている。

- いつかみが提供できる商品欄に、番外編としてキリスト教企業・団体の紹介などができることを明示させてあることの確認。

- かすがは、基本的にはサイト売却はしない方がいいと考えている。

- 両者とも、いつかみは、趣味・遊びとして作っているわけではない。完結後は放置してもう手入れしないという考えではないことを確認した。

- 他のLampMate企画もあるが、いつかみは第一の商品で、第一の種まき。完結によりすぐに収穫にまでたどり着くかは不明。それを測定するためのサンプルとしていつかみを機能させる。

- コンセプトを絞って制作した結果、商品として機能するかを判断する。もし商品として機能しないとしても、その報告をすることで次に続く人への価値を提供できると考える。

- 有料Noteにて、制作過程、ハウツー、PV数などを販売する。11月30日に完結した場合、2週間後、12月中旬に有料販売予定。1年後、サイトが伸びている様子を追加報告販売する。伸びていない場合も報告する。

- いつかみを始める当初に設定したPDCAの再確認。
Plan…雑誌サイトとして、コンセプト重視、クオリティ重視のサイト制作をし、対象年齢30人に1人にアプローチし、その効果をキリスト教界隈に伝え、商品化する。
Do…1年でストーリーを完結させる。
Check…商品化としての整合性が取れているかの確認。
Action…販売と実績のアピール、認知度向上の施策、（英語圏へのアプローチ強化）など。



## 代替案

- ストーリーを脇に置き、収益化を先に着手する。1か月間を一つのPDCAサイクルとして、1か月での商品売り込み期間の成果により今後の判断をする。

- 終了

**Comment by uesakaeita** [comment]
両者、文章のチェックをし、方向性の一致と確認ができたため閉じます。

必要に応じてreopenしましょう。
