### ISSUE TITLE
第14話　灰羽連盟

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#164]
◆ 14話　お楽しみ2（見せかけの成功の途中）
【取り上げるマンガ】灰羽連盟１
【登場人物】　葵　石本　ラビー
【場所】教会牧師館
【葵の心の変化】「いいことを積み上げていけばいつかそれが自分の本質になるんじゃないかな」
【葵の行動の変化】「YOUTUBERうぇええい」
【取り上げるキリスト教エッセンス】「信仰義認と罪」

![jpeg -7e26e0315e4a-1](https://user-images.githubusercontent.com/33079296/42859588-d7182470-8a8e-11e8-834c-0f05859acbed.jpeg)

**Comment by kasugamori** [comment]
![img_4817](https://user-images.githubusercontent.com/33079296/45536698-30709300-b83d-11e8-8554-f62a7aec9c77.JPG)

**Comment by uesakaeita** [comment]
本編14話、11月上旬に投稿完了です！

あとは、
・灰羽連盟のコラム
・煉獄記事

を進めていきたいですね。
両方とも8割程度はできているので、残りを進めていきたいですね。
