### ISSUE TITLE
記事を会話形式にするためにキャライラスト挿入

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#19]
2017/11/17　8:00までに返事がほしいです。キャラクター挿入開始前に確認おねがいします。

**Comment by kasugamori** [comment]
![chara-aoi-nameiri125](https://user-images.githubusercontent.com/33079296/32824500-911a203e-ca24-11e7-818d-3eedfb78ecd9.png)

**Comment by kasugamori** [comment]
口頭で了承もらいました。閉じます

**Comment by kasugamori** [comment]
125×約125の形で作りましたが、スマホで表示した時に少し大きい気がします。
（トリイさんのが100で、松原さんのが150でしたから、中間をとりました）
いっそ100くらいにしてみたいと思うのですが、いかがでしょうか。

**Comment by uesakaeita** [comment]
プロローグのキャラクターが125×125なのでしょうか。
もう少し小さくて良いと思います。

100×100を作って、見せてもらえますか？

画像の差し替えは、まとめてできる方法を探したいと思います。
sarch＆replace　の何かで、すぐできると思います。

**Comment by kasugamori** [comment]
![chara-aoi-nameiri100x97](https://user-images.githubusercontent.com/33079296/32931521-fa380304-cba7-11e7-858b-6a0efa7b9f8e.png)
![chara-ishimoto-nameiri100x105](https://user-images.githubusercontent.com/33079296/32931523-fb021d1a-cba7-11e7-9336-1b4271b5bf05.png)
![chara-takumi-nameiri100x106](https://user-images.githubusercontent.com/33079296/32931524-fc56ae1a-cba7-11e7-97c4-5a1f9d250d7a.png)

**Comment by kasugamori** [comment]
現在ある４本の記事はキャラクターを手差しで挿入します。21日火曜日に、何かしら一括でできる方法を栄太さんが報告してくれるとのことで、楽しみにしています。

**Comment by uesakaeita** [comment]
プラグイン入れて説明しました

**Comment by kasugamori** [comment]
100X100で進めています。大きめの画像を貼り付けて、WP上で縮めると画像が綺麗なため、それで行うこととしました。手挿入です。
