### ISSUE TITLE
タイトル案聞いた人たちに、報告も兼ねてリンク添付

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#21]
11名予定。

**Comment by uesakaeita** [comment]
楽しみですね！

**Comment by uesakaeita** [comment]
**栄太からのコンタクト予定**
・大泉学園のD.Tさん→12月2日、リンクを送りました。感想は教会で聞いてみます。

・BWのNさん→1月下旬　→　見てもらった

・草加のKちゃん→1月上旬　→　見てもらった

**Comment by kasugamori** [comment]
**かすがコンタクト済み一覧**

・ブロガーAさん　→　見てもらった

・Sさんカップル　→　見てもらった

・北海道Yさん　→　見てもらった

・クリスチャンでないHELLSING好きのYさん　→　ヘルシングを記事に取り上げたら紹介する

・愛知のNさん　まだ？
・栄太さんと共通の知人Mさん　→　まだ


**これからコンタクト予定**
・週一通話しているMさん　→　まだ

**Comment by uesakaeita** [comment]
・沖縄のNくん→　見てもらったっけ？
Nくんは、GitHub経由で見たという話しでしたが、
直接リンクを送ったりはしていなかったと思います。
