### ISSUE TITLE
自所有ブログ「存在に〜」にリンク添付する用バナー作成

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#22]

**Comment by kasugamori** [comment]
昨日空き時間に作ったものです。個人ブログからの誘導に使えるかと思い作ってみました。
![itukamitxt](https://user-images.githubusercontent.com/33079296/32866826-f6067582-caac-11e7-8976-e4d68e80d255.png)
![itukamitxt2](https://user-images.githubusercontent.com/33079296/32866831-f9aecb1c-caac-11e7-8cf4-8bcc8df04241.png)

**Comment by uesakaeita** [comment]
すごい！

**Comment by kasugamori** [comment]
息抜きに作りました。所要時間は約30分です。「認知的不協和」を利用したアイデアを参考にしました。バナーは奥が深いので色々実験して行きたいです。
![itukamibanner](https://user-images.githubusercontent.com/33079296/32870015-4246641a-cabd-11e7-8d6e-0c331fd8fe20.png)

**Comment by kasugamori** [comment]
・今後バナーでやってみたいこと
→「ユーザーボイス」「ユーザーメリット」を打ち出したバナー
→具体的な数字を混ぜる

※現在、自分で所有しているサイトでしか掲載を考えていないので、サイズそのものは考慮していない。
多いのは300×600や、336×280だそうです

参考サイト→http://buildupp.net/webdesign/banner-design-psychology

**Comment by uesakaeita** [comment]
すごくいいと思う。やっぱりキャラクターがいた方が目を引きますね！

**Comment by kasugamori** [comment]
昨日息抜きに作りました。横長バナーです。自ブログの途中に入れる用です。
![itukamibannaryokonaga](https://user-images.githubusercontent.com/33079296/32921756-1a33ac7a-cb72-11e7-983f-6ca11ad536be.png)

**Comment by uesakaeita** [comment]
拓海くんはおらんのか
