### ISSUE TITLE
脚本家の名前と紹介について

### ISSUE THREAD

**Issue by uesakaeita** [lampmate/itukami#23]
Sさんの名前を出すかどうか。
リンクを張っていいか、本人に聞いてみるか。
感想を聞いてみるか。

**Comment by kasugamori** [comment]
私は大きな影響をいただきましたので、「その旨を伝える」ことはぜひともしたいと考えています。その流れでリンクや名前を出していいか伺っていただけますか？感想もいただきたいです。

**Comment by uesakaeita** [comment]
分かりました。
12月中に連絡しましょう。
そのころにはデザインも落ち着いていると思います。
