### ISSUE TITLE
サブタイトル「とあるマンガの聖書解説」について

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#25]
2017/11/16　11:59までに決定しておきたいです。

統一するのかしないのか？するとしたら

1.いつから僕らは神を知らないと錯覚していた？〜とあるマンガの聖書解説（バイブルメタファー）〜
なのか
2.いつから僕らは神を知らないと錯覚していた？とあるマンガの聖書解説〜バイブルメタファー〜
なのか。

**Comment by uesakaeita** [comment]
1がいいです。

**Comment by kasugamori** [comment]
了解しました
