### ISSUE TITLE
ペルソナの設定・ペルソナのサクセスストーリー設定

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#26]
【現在決まっていること】
・ペルソナA(葵に移入)
「◯◯ってマンガが好き」→「(ツイッターかグーグル検索)読んでる人いないかなー？どんな感想持ってるのかなー？」「コラムとか読むタイプ」→「あー、私ってキリスト教のこと知ってたんだ…」
 
・ペルソナB(拓海に移入)
「マンガを描きたい(なにかしら作品を作りたい)」「聖書のことを知識として知っておきたいとは潜在的に思ってる」→いろいろあって→「俺ってキリスト教のこと知ってたんだ」「ですよねー」「やっぱそうだったんだ」「目からウロコ」（自分も投稿したい）
ーーーーーーーーーーーーーー
1サイトで違うペルソナがあることは問題ないようです。ただ、それぞれ目的が違うので、各ペルソナが回遊しやすいようにしておく必要はあるようです。

**Comment by uesakaeita** [comment]
そうですね。

lampmateの企画の、サービス3に該当するという方針で進めていたため、
彼ら彼女らの次のステップとゴールをどこに定めるかによって、ペルソナの幅が変わってくると思います。

それぞれにとって見やすいサイトにしていきましょう！大賛成です😄
