### ISSUE TITLE
カテゴリー・タグについて

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#27]
カテゴリを作成していると、タグの必要性がないサイトなのではないかという気がしてきました。

タグ作成は後でもいいかな？という気がしています。
http://affikatsu.com/category-tag-1482/

**Comment by uesakaeita** [comment]
11月27日ミーティングにて

④カテゴリーについて→SEO的にも、ユーザー目線にする。1記事１カテゴリーが本サイトに該当するかは未定。紙とフセンで客観的に決めたい。1時間ミーティングの時間を取りたい。お互いにアイデアを考えた上でもちよる。→意見が割れたら監修、ユーザーに相談する。

ーーーーーーーーーーーーーーー
【かすがの意見】
・カテゴリ/取り扱いたいマンガタイトルはあらかじめ出しておいた方がユーザーに親切

**Comment by uesakaeita** [comment]
1記事１カテゴリーが本サイトに該当するかは未定。

1時間ミーティングをし、紙とフセンで客観的に決めましょう。

お互いにアイデアを考えておきましょう。
→意見が割れたら監修・ユーザーに相談する。

ミーティングの日程未定

**Comment by uesakaeita** [comment]
2月2日 ミーティングにてカテゴリー、タグの分類が決まりました。

写真を投稿します。

**Comment by uesakaeita** [comment]
![c5b13102-04cd-448b-b67f-5186feb66985](https://user-images.githubusercontent.com/33074227/35720633-e6d29af6-0831-11e8-89d3-dc6ed2d5be1d.jpeg)

**Comment by uesakaeita** [comment]
2018年3月、サイト全体像の大幅修正があったため、
カテゴリーとタグについて、再度まとめておきたいと思います。


また、カテゴリー一覧のページでの

1. 表示用のタイトル作成

1. ディスクリプション、

1. メタディスクリプション

1. アイキャッチ画像

についても決めたいと思います。

https://saruwakakun.com/sango/seo-category

**Comment by uesakaeita** [comment]
2018年5月21日ミーティングで話し合いました。

本編記事に関しては、
1記事2～3カテゴリーはOKとします。

コラム記事に関しては、
メインカテゴリーは「コラム」
サブカテゴリーに2～3カテゴリーOKとします。

**Comment by uesakaeita** [comment]
2018年5月21日ミーティングで話し合いました。

ディスクリプションを入れましたが、まだ未完了です。
次回持ち越しです。
