### ISSUE TITLE
サポート→「ドネーション」については公開初期は消した方がいいのでは（様子を見てつける）

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#28]
サイト初期は、誰もが警戒心を持っていると思います。また、「いつ神」のターゲットは未成年なので、あまりそういった面を出さない方がいいかなと思いました。収益源なし→アプリアフィリエイト→様子を見てドネーション依頼（もしくはlampmateの方に統一？）はいかがでしょう。

**Comment by uesakaeita** [comment]
概ねそうだと思います。
ここでドネーションと称しているのは、サポート全体のことを指していますか？

サポートの1つとしてのドネーションのことですか？

サポートのページは公開時から入れますが、欲しいものリストは記事数が溜まってからがいいと思っています。

現金振り込みドネーションは、入れなくていい、またはlampmateに統合で考えています。

**Comment by kasugamori** [comment]
いいえ、「サポートの中のドネーション」の項目についてです。

栄太さんに賛成です。取り急ぎドネーションの欄だけ消していきます。

**Comment by uesakaeita** [comment]
サポートの検討事項
・クラウドファンディング
・欲しいものリスト
・ポルカ？
・LampMateでのドネーション？
