### ISSUE TITLE
骨子提示issue

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#29]

**Comment by kasugamori** [comment]
今週石川先生にサポートしてもらいたいので、次回作もぼちぼち書き始めます。

また、12/1の映画公開に間に合わせたいです。

ーーーーーーーーーー

【鋼の錬金術師】
・キャラクターの魅力

欠点が必ずある
エドマスタング
→罪を認めている人間の魅力

・ウィンリィの両親は隣人愛の実践者
しかし物語の構成上  死ななくてはならない



・等価交換の法則は世界の法則として描かれるし、読み手もそこに納得するから厚みのある物語として受け入れられた。最終的に主人公が選ぶのは、等価交換を超えた「愛」とも呼べる選択肢である。


ーーーイエスの十字架は等価交換を超える「与える愛」を尊いと感じるならば、キリスト教のことを知ればそこに何か思うところができるはず。

**Comment by uesakaeita** [comment]
第5話、見させていただきました。

修正も多少しましたので、このissueはcloseして大丈夫だと思います。

各話ことにissueを作りますか？

**Comment by kasugamori** [comment]
ここには、各話の骨子を重ねていきます。

**Comment by kasugamori** [comment]
次回作になるかどうかはわかりませんが、「ヒカルの碁」の骨子です。
![img_2670](https://user-images.githubusercontent.com/33079296/33469490-905cd52c-d6a6-11e7-8cf7-886f9724fa69.JPG)

**Comment by uesakaeita** [comment]
いいねこれ！
クリスマスネタはいったん置いておいて、ひかご着手をお願いします！

『砂の上の足跡』の話を思い出しました。使えそうだったらどうぞ。

http://www.ieji.org/archive/footprints-in-the-sand.html

https://www.christ-hour.com/archive/detail.php?id=138

**Comment by uesakaeita** [comment]
提案です。
各話ごとに、issueを作りたいのですが、いいでしょうか？

そうすることで記事ごとの投稿場所がまとめられると思います。
『〇話かすがさんの骨子を投稿 → 石川監修チェックの記録 → 栄太監修チェックの記録』という流れはどうでしょうか。

メリット
①プロジェクトに反映させることで、進捗を管理しやすくできる
②のちのち栄太の監修チェックissueを作るのであれば、issueの数は変わらないのだし、話数ごとに残すことができる
②記事作成の経緯・背景を知りたくてGitHubに来た人が見たら絶対楽しいと思う
③

デメリット
①骨子一覧という見方はできない。←必要ない？
②
③

いかがでしょうか。返事待ちのラベルにしておきます。

**Comment by kasugamori** [comment]
賛成です。でもこのissueは閉じます。現在制作中の「6話ヒカルの碁」用につくるところから始めます。
