### ISSUE TITLE
メニューの検討

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#3]

**Comment by uesakaeita** [comment]
はい、栄太が対応します

**Comment by kasugamori** [comment]
お願いします

**Comment by uesakaeita** [comment]
だいたい今のメニュー構成でいいでしょうか？
大丈夫でしたら、このissueを閉じて、プロジェクトの進捗を完了に進めてください。

10記事ほど溜まった頃には、またサポートも含めてメニューを再構成したいと思います。
