### ISSUE TITLE
グーグルアドセンスへの申請

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#31]
サブドメインでの申請はダメ？

https://support.google.com/adsense/answer/2784438?hl=ja

**Comment by uesakaeita** [comment]
リンク先、読みました。

この内容からは、特にサブドメインは使えないって思いませんでした。

大丈夫なのでは？

**Comment by uesakaeita** [comment]
できないんね。

**Comment by kasugamori** [comment]
グーグルアドセンス導入後、《このサイトについて》にてお断りの文言を挿入忘れないようにする。

**Comment by kasugamori** [comment]
サブドメインでの申請ができないため、一旦閉じます。
