### ISSUE TITLE
章構成について

### ISSUE THREAD

**Issue by uesakaeita** [lampmate/itukami#34]
ストーリーは、
章ではなく、話にしましょう。

**Comment by uesakaeita** [comment]
返事お願いします

**Comment by uesakaeita** [comment]
プロローグは1話にした方がいいと思います。
本編は2話からにしたいです。

理由
テーブルの見栄えがいいから。

**Comment by kasugamori** [comment]
了解しました。また、記事タイトルは全て（4話まで）修正済みです。それ以外の部分の修正（テーブル？）はお願いします。
