### ISSUE TITLE
「ネット乞食」という概念とどう付き合っていくかについて

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#36]
http://eraitencho.blogspot.jp/2017/11/blog-post_23.html
↑
ブログを読んでいただけると幸いです。ネット上で金銭を受ける場合のノウハウが載っているので、（今まで私のなかで言語化できてなかった部分を言語化されていると感じる部分が多くありました）参考になりそうだと思いました。
アフィリエイトで運営費をまかなえなかった場合の次の施策として予防線を張っておく必要があるのかなと思いました。

**Comment by uesakaeita** [comment]
はい。読みました。

**Comment by kasugamori** [comment]
清さや正しさのハードルは下げておいた方がいいのかなと思いました。どこかに「運営費はアフィリエイトにてがんばって賄う予定ですが、ダメだったら別に施策をとります」くらいの予防線は張っておくといいのかなーと思っています。いかがでしょう？

**Comment by kasugamori** [comment]
当面はアプリアフィリエイトやアドセンスで頑張るので、今の所ここについてて方向性を変える必要はないかなと思いました。（「初めての方へ」のところに、広告収益は運営費に充てると但し書きもしましたし、「応援方法」にサイト内で紹介してるサービスなどを使ってみると応援になりますとも書き足しました。）とじます。

**Comment by uesakaeita** [comment]
はい、分かりました。
当面は現状の記載でいいと思います。
ありがとうございます！

閉じます
