### ISSUE TITLE
次回ミーティングで話したいことメモ

### ISSUE THREAD

**Issue by uesakaeita** [lampmate/itukami#37]

**Comment by kasugamori** [comment]
①画像に外部リンクを付与する場合、別タブにしたい。（例えばyouversion）
→について。

画像であろうがなかろうが、外部リンクは基本的に別タブで進めています。
別タブになっていないものがあったらそれはモレなので、気づいた人がその場で修正・もしくは報告してください。

**Comment by uesakaeita** [comment]
了解しました！気づいた人が直すという方向で賛成です。

では、youversionのリンクが別タブでなかったので、見つけたら直しておきます。12時間以内ルールは、今回はできない可能性が高いですが。

**Comment by uesakaeita** [comment]
11月27日ミーティング　12:45～13:45
かすがさん話したいこと
①クリスチャンの方へ
②メニュー
③ハガレン
④所属教会について
⑤サポートについて
⑥クリスチャンでない方へ


栄太が話したいこと
①画像に外部リンクを付与する場合、別タブにしたい。（例えばyouversion）
②いつかみ、の表記について
③制作、製作について
④カテゴリーについて
⑤記事の最後の、ライター画像について

**Comment by uesakaeita** [comment]
次回ミーティングで話すこと

テーブルの作成について

**Comment by uesakaeita** [comment]
転記済みのため、closeします
