### ISSUE TITLE
テーブルの使い方について

### ISSUE THREAD

**Issue by uesakaeita** [lampmate/itukami#38]
プラグインの使い方を説明します。
時間できたらここに書く、または、ミーティングで説明します。

よろしくお願いします。

**Comment by kasugamori** [comment]
必要なことは教わりました。「画像を左寄せにするか？」という問題点のため、issueは残しておきます。

**Comment by uesakaeita** [comment]
12月4日ミーティングにて

現記事は左寄せにしてあります。

まだ仮状態なので、テーブルの修正は栄太が担当します。

確定したら、かすがさんに担当してもらうかもしれません。

とりあえずcloseします。
