### ISSUE TITLE
キャラクターイラストに名前をテキストで表示

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#4]

**Comment by uesakaeita** [comment]
@kasugamori 
どの画像に、どのように名前を入れるか考える必要があります。

まずは、対象となる画像を私にください。

よろしくお願いします。

**Comment by kasugamori** [comment]
この件は私が引き受けます。公開までに行いたいと考えていますので。一度私が行なって、できなかったときはお願いするかもしれません。

**Comment by uesakaeita** [comment]
分かりました！

出来なさそうだったら言ってください🙇
