### ISSUE TITLE
かすが母教会への連絡について

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#40]
管理人プロフィールを書いていたら、流れ的に自分が洗礼を受けた教会のことも書いた方が自然な気がしてきました。小松島栄光教会への連絡はいかがしましょう？

**Comment by uesakaeita** [comment]
なるほど、分かりました。
小松島栄光教会のことを書くかどうかですが、それが自然かどうかいまの文章ではちょっと分かりませんでした。

提案ですが、一度、その文章を見せてもらうことは可能ですか？

①今の状態のプロフィールをコピペして残しておく
②小松島栄光教会のことを書いたプロフィールを書いてみる
③比較検討する

この3ステップで見せてもらえたら、私としては判断しやすく助かります。
自分の判断で、絶対書いた方がいいと思うのでしたら、比較検討しなくていいですが……

文字数や他の人との全体のバランスも考慮する必要があると思います。
見せてもらえたら判断しやすいのですが、いかがでしょうか？

**Comment by kasugamori** [comment]
今は優先度高くないと判断しました。一旦閉じます。
