### ISSUE TITLE
テーマの変更について

### ISSUE THREAD

**Issue by uesakaeita** [lampmate/itukami#41]
2017年11月27日12:00現在
フリーのワードプレステーマHestiaを使っています。

かすがさんの休憩のタイミングで
フリーのワードプレステーマXeoryExtensionに変更したいと思います。

バックアップは取りました。

所要時間、30分ほどください。

何時に休憩に入りますか？

**Comment by kasugamori** [comment]
では12:00〜12：30、ワンノートの作業に移ります。

**Comment by uesakaeita** [comment]
了解しました。
テーマ変更に入ります。

**Comment by uesakaeita** [comment]
テーマ変更しました
