### ISSUE TITLE
サイト内で紹介するキリスト教関係のコンテンツ候補

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#44]
●キリスト教って何？ノンクリスチャンの私が初めて教会に行ってみた
→http://www.radflumpool.com/entry/christian-ru-terukyoukai-reihai

●あやめディア
→http://ayamezum.com

●マツヤマカンキ氏のブログ
→http://wemmick3.com/category/christian/

**Comment by kasugamori** [comment]
あやめさんのブログはこちらに載せていました。
→http://ayamezum.com/

**Comment by uesakaeita** [comment]
質問です。

これら「サイト内で紹介するキリスト教関係のコンテンツ」は、コラムに投稿で考えているのでしょうか？

まだコラムの方向性が定まっていない為、周辺情報としてはコラムでも可能かと思います。

ただ、コラムは本編で描けない話、補足情報に限定するなら、

「サイト内で紹介するキリスト教関係のコンテンツ」は別の固定ページを作か、LampMate親サイトでの記事になると思います。

なので選択肢としては

1.いつかみのコラム
2.いつかみの別固定ページ
3.LmapMateの記事
4.いつかみでもLmapMateでも記事にする

が考えられます。


どう考えていますか？

私は、サイトの方向性、全体像とも関わってくる話なので、監修者に相談してみてもいいかなと思っています。

**Comment by uesakaeita** [comment]
12月4日ミーティングにて

かすがさんの考え　3.LmapMateの記事　に賛成

栄太の考え　3.LmapMateの記事　に賛成　いつかみと親和性がある場合は、4.いつかみでもLmapMateでも記事にしてもいいと思っています。

**Comment by uesakaeita** [comment]
ミーティングの結論としては、

3.LmapMateの記事　で進めていきましょう。

LmapMateのサイトは、12月に栄太が担当しますので、必要になったらまた相談に乗ってください。

よろしくお願いします。

colseします
