### ISSUE TITLE
カテゴリについて

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#45]
11月27日ミーティング引用
④カテゴリーについて→SEO的にも、ユーザー目線にする。1記事１カテゴリーが本サイトに該当するかは未定。紙とフセンで客観的に決めたい。1時間ミーティングの時間を取りたい。お互いにアイデアを考えた上でもちよる。→意見が割れたら監修、ユーザーに相談する。
ーーーーーーーーーーーーーーー
【かすがの意見】
・カテゴリ/取り扱いたいマンガタイトルはあらかじめ出しておいた方がユーザーに親切

**Comment by uesakaeita** [comment]
タグについてとまとめます。closeします
