### ISSUE TITLE
固定ページ

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#48]
毎週月曜日21:00更新と、おちついたら追加する→2018年2月16日、なしの方向にしましょう

**Comment by uesakaeita** [comment]
かすがさん、お願いがあります。

全然急ぎではないので、固定ページのアイキャッチを作ってもらってもいいでしょうか。

アイキャッチのサイズの統一が決めていないので、本当に簡易的なもので大丈夫です。（次回？ミーティング予定項目）

キャラクター紹介
https://itukami.lampmate.jp/newcomer

よくある質問
https://itukami.lampmate.jp/faq

このサイトについて
https://itukami.lampmate.jp/site

お問い合わせフォーム（なくてもいいかな）
https://itukami.lampmate.jp/contact


よろしくお願いします。

**Comment by kasugamori** [comment]
キャラクター紹介→完了
https://itukami.lampmate.jp/newcomer

よくある質問→完了
https://itukami.lampmate.jp/faq

このサイトについて →完了
https://itukami.lampmate.jp/site

お問い合わせフォーム←なくてもいいと思います
https://itukami.lampmate.jp/contact

**Comment by uesakaeita** [comment]
ありがとうございました！
閉じます。

**Comment by kasugamori** [comment]
余計な固定ページを削除予定（栄太さんが）

**Comment by uesakaeita** [comment]
はい、すみません。削除しました。
