### ISSUE TITLE
2話　魔法使いの嫁　監修チェック中

### ISSUE THREAD

**Issue by uesakaeita** [lampmate/itukami#54]
![img_9076](https://user-images.githubusercontent.com/33074227/33417920-cfe4a8b6-d5e6-11e7-965f-d727580ba5f2.PNG)

この画像、変更してもいいのかなぁと思いました。

もう一つの候補画像があったでしょうか。

「チセの生きる動機はエリアスが望むから」という小見出しなので、今のはちょっと流れ的に変かなぁと思いました。

チセの希望を持ち始めたような、生きようとしているシーンの画像にしてはいかがでしょうか？

べっ、べつに嫉妬的なのとかじゃないんだからね！

**Comment by kasugamori** [comment]
記事内にチョイスする画像は、「こんなシーンあるんだ！読みたい…_:(´ཀ`」 ∠):」となるようなものでいこうと考えています。

観ている人も反射的に読むと思うので、あまり前後の文脈は考えなくていいかなと思ってます。

いかがでしょう。

**Comment by uesakaeita** [comment]
栄太メモ
・画像の出典のリンクが抜けている
・文章の位置の修正
・行間の修正
・文字の色の修正？

**Comment by kasugamori** [comment]
コラム：魔法使いの嫁を書きました。ワンノートにありますのでチェックお願いします。
・目的は①と②に該当します。キーワードは「魔法使いの嫁　チセ」を狙っていますが、コンテンツのオリジナリティを優先してるのであまり深くは考えてません。
・魔法使いの嫁２クール目が終わらないうちにアップ希望します
・ドメインを育てたいので、細かい整合性よりもアップを優先してほしいと思っています。この程度のクオリティの記事であれば十分だと思います。

**Comment by kasugamori** [comment]
魔法使いの嫁とルツ記が似ている、と監修が言われていたので、その切り口で聖書の書簡をプレゼンしてもいいのかなぁと思いました。
![img_3520](https://user-images.githubusercontent.com/33079296/35957888-352e105a-0ce1-11e8-9e2c-0acc1506c43e.JPG)

**Comment by uesakaeita** [comment]
承知しました。
２月１３日～確認します。
