### ISSUE TITLE
1話　プロローグ

### ISSUE THREAD

**Issue by uesakaeita** [lampmate/itukami#55]
![img_9077](https://user-images.githubusercontent.com/33074227/33420539-5739fa36-d5f2-11e7-981f-41df062152e9.PNG)

点数独り占めってあるの？
石川監修官は何かおっしゃってましたか？

**Comment by kasugamori** [comment]
・「点数独り占め」は石川伝道師は何も言ってないですよ？これは私の作った架空の新興宗教ですから、私が「ある」と言えばあります。
・石本さんは過去にとある新興宗教団体の幹部生だったという過去を持ってる感じにしようと思ってます。ここで葵に嘘を言ってるのは、別に言う必要がないからです。いつかみが進んでいったら明かされていきます。

**Comment by kasugamori** [comment]
新興宗教の女性のイラスト、独自で作ってアップロードしなおしました。確認お願いします。

**Comment by uesakaeita** [comment]
女性のイラスト、確認しました！とてもいいと思います！



h3小見出しを２つほど作り、分割したいと思います。

ミーティングの時に、場所の相談をさせてください。

**Comment by uesakaeita** [comment]
2月5日　ミーティングにて

挿入しました。closeします

**Comment by kasugamori** [comment]
プロローグ、「約束の丘（いのちの木の丘）」画像を入れたり、今後の伏線をいくつか挿入します。作ってあるので次回ミーティングで確認お願いします。

**Comment by uesakaeita** [comment]
## 2月15日ミーティングにて

画像の挿入、導入部、結部など、ミーティングにて修正しました。
ありがとうございました。

**Comment by kasugamori** [comment]
プロローグ画像などの修正完了です。閉じます。
