### ISSUE TITLE
3話　恋雨　監修チェック中

### ISSUE THREAD

**Issue by uesakaeita** [lampmate/itukami#56]
![img_9081](https://user-images.githubusercontent.com/33074227/33423775-289c966a-d5fd-11e7-830f-a65fbe5dd71b.PNG)

まだサラっとしか読んでないのですが、
この箇所がよく分かりませんでした。

お母さんは、なんか変わったんでしたっけ？

**Comment by uesakaeita** [comment]
![img_9082](https://user-images.githubusercontent.com/33074227/33424092-1bbc61c2-d5fe-11e7-9144-397b7bb30665.PNG)


次の水曜日に、石川先生に確認したいです。私個人の関心としても。

**Comment by kasugamori** [comment]
・お母さんが変わったのは「マンガも面白いのね」という感想を抱いて、自身もマンガを読み始めたことです。葵は学校や家でマンガの話をできる環境がないからこそ、話を聞いてくれる石本さんのところに通っているのでしょう。お母さんが読んでいる、というくだりを入れざるをえなかったのは、恋雨は葵の年齢だと楽しめないまんがだと判断したからです。

・聖書箇所についての整合性は、すでに私では判断できないので、監修におまかせします。

**Comment by kasugamori** [comment]
コラム書きました。onenote→いつ神聖書解説→コラム→コラム　恋は雨上がりのように

に掲載していますので時間あるときにチェックお願いします。

**Comment by kasugamori** [comment]
あまりにも遅いので、私の方でコラムを下書きアップしました。今は記事に質云々よりも記事数も大事だと思います（ドメインパワーをあげたいですし）。チェックして投稿お願いします。
