### ISSUE TITLE
キャラクターの性格について

### ISSUE THREAD

**Issue by uesakaeita** [lampmate/itukami#57]
# 葵さんの性格と今後の変化

葵さんは、3話目では「……」が多いように思いました。
落ち込んでいるわけではなく、控えめキャラで、まだ石本さんとの関係に緊張があるから、そういった描写にしているのでしょうか。

次第に石本さんと打ち解けていくにつれて、変わってくるのかなっといった印象ですが、いかがでしょうか？

# 拓海くんの性格と今後の変化

# 石本さんの性格と今後の変化

**Comment by kasugamori** [comment]
・3話で葵のセリフに「……」が多いのは、葵自身は「恋雨」を面白いと思えず、その面白さをさぐっているという構成からそういうニュアンスになつたのだと思われます。整合性を優先して修正していただけたらと思います。葵と石本伝道師の関係性はそんなに変わることはないと思います。葵は66話までイエスのことを信じません。

**Comment by kasugamori** [comment]
・拓海は、葵よりもたくさん66話の中で揺れ動き、変化していく予定です。信じかけたり、周りの目が気になって信じれなかったりしてもらおうかなと思います。何回か。

**Comment by uesakaeita** [comment]
wikiに転記しました。
ここはcloseします。

**Comment by kasugamori** [comment]
拓海のキャラ紹介案（聖書の学びが終わる話まで使用可能？）
→　葵に連れられてとある教会にやって来た15歳。マンガ家を目指す熱血少年。聖書の勉強を受けている途中。石本のことを好きではあるが、目に見えないモノのことは信じていない。
 
拓海用あらすじ案（聖書の学びが終わる話まで使用可能？）

→春。幼馴染の葵に連れられ、とある教会牧師見習い・石本に出会った拓海。鋼の錬金術師の話をきっかけに、聖書について学ぶようになる。

**Comment by uesakaeita** [comment]
いいと思います。転記したのでcloseします。
