### ISSUE TITLE
4話　けもフレ　監修チェック中

### ISSUE THREAD

**Issue by uesakaeita** [lampmate/itukami#58]
![img_9094](https://user-images.githubusercontent.com/33074227/33431038-323b9810-d616-11e7-8339-8d7c602c524c.PNG)

この、隠居してないですよー;の
セミコロンは、誤字？それとも汗的なのですか？

**Comment by kasugamori** [comment]
汗的なものです。

**Comment by uesakaeita** [comment]
タグの相談です。

テーマ変更にあたり各話のカテゴリーとタグを修正しました。

けものフレンズのタグは現在
アドベンチャー、アニメ作品、死後の世界、に設定してあります。

死後の世界、は必要ないでしょうか

死後の世界タグは決して、ディストピアというタグを設定してもいいでしょうか。

**Comment by kasugamori** [comment]
「BLEACH」「死役所」などが【死後の世界】に該当します。【ディストピア】だと少し違うイメージになります。ディストピアタグを別に作りましょうか。

**Comment by uesakaeita** [comment]
返事ありがとうございます！
【ディストピア】のタグの作成をしますね。

**Comment by kasugamori** [comment]
「けものフレンズとは？」の説明のところに、画像ではなくYOUTUBEを埋め込みました。（公式の「ようこそ！ジャパリパークへ」の映像です）

けもフレはそもそもアニメ作品ですし、主題歌はMステにも出演したので認知度もあるのでこれがベストなような気がしてきました。いかがでしょうか？

**Comment by uesakaeita** [comment]
とても素晴らしいアイデアだと思います！

ありがとうございます。

完了とし、クローズします。
