### ISSUE TITLE
著者紹介について

### ISSUE THREAD

**Issue by uesakaeita** [lampmate/itukami#59]
いらないかなと思えてきました。
理由①画像の横に縦長に文章が入り、見栄えが悪い。
理由②ゲストライターはそのための枠やページを作ってもいい。現状のスペースだけではせまいから。

そのため、著者紹介はなしにし
2カラムにして著者紹介やテンプレ事項を入れておく、というデザインを検討しています。

違和感あったら教えてください。よろしくお願いします。

**Comment by kasugamori** [comment]
2カラム賛成です。
