### ISSUE TITLE
「初めての方へ」を各話上の方へ記載

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#60]
ハガレン記事から入って来た人は「？？？？」となるので、各話の上の方に「キャラ紹介」などを挿入していきます。

**Comment by uesakaeita** [comment]
あー、確かにだわー

ありがとうございます！

**Comment by kasugamori** [comment]
現在アップされている2話〜5話まで行いました。wikiにも「アップロード時に気を付けること」に追記しました。
