### ISSUE TITLE
脱依存メルマガにいつ神リンクを添付して送信

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#61]
現在メルマガ整理中。

**Comment by uesakaeita** [comment]
了解。

**Comment by kasugamori** [comment]
12/16（土）20:00に182通配信されました。今後は「脱依存メルマガ」登録の方に、登録日より25日後に配信されていくよう設定してあります。

ちなみに、添付したアドレスのクリック数は9件の模様です。（メルマガ内には「いつかみ」トップページのURLと「あなたも書いてみませんか？」のURLを添付しています。）また、口頭でもお伝えしましたが、お一人の方から「協力できることがあれば」というメールをいただきました。

問題なければこのissueを閉じてください。

**Comment by uesakaeita** [comment]
見たよ！
