### ISSUE TITLE
第6話　ヒカルの碁

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#64]

**Comment by uesakaeita** [comment]
![6](https://user-images.githubusercontent.com/33074227/33516436-19967612-d7b6-11e7-9045-114c47c3636e.JPG)

骨子issueからの転記です。

**Comment by uesakaeita** [comment]
（下記コメント、骨子issueからの転記）

いいねこれ！
クリスマスネタはいったん置いておいて、ひかご着手をお願いします！

『砂の上の足跡』の話を思い出しました。使えそうだったらどうぞ。

http://www.ieji.org/archive/footprints-in-the-sand.html

https://www.christ-hour.com/archive/detail.php?id=138

**Comment by kasugamori** [comment]
（石川先生監修チェック）
・父・子・御霊で等しい存在
　→父（人格ある）子（人格ある）という点から、三段論法的に聖霊も人格がある、と説明されることがある。呼び方は違うけど同じものだから、聖霊も人格があると説明することができる。
　→神様を愛することは「心を尽くして思いを尽くして精神を尽くして」とある。「神様は霊的な存在だけど、ここには「人格的な勧め」があることから、聖霊も人格があると言えるのではないか。（感情的な恍惚状態というよりかは幅広い）
　
 
・佐為のことは、聖霊にたとえるより「御使い」に例える方がよくない？のことで語れないか？
 
・「聖霊」を語りたいなら、
 
→「御使い」がマリヤに語られるときは「聖霊の働きがある。背後で聖霊が働いてくださっている。ヒカルを助ける霊的な働き。「一般恩寵」神様はどんな人にもある。
 
 
・聖霊はすべての人に働いているといえるが、（クリスチャンでない人にも）
→ひろげすぎると、「その霊、どの霊？」となるから、非常に扱いにくい。取り扱いは注意すべし。
 
 
「聖霊論」
・ペンテコステには聖霊が降った。（イエス様が言った「助け主が送られる」）
・それ以前に聖霊はいなかったのかどうか？→いたはいた。
・ルカ：バルテスマのヨハネ3:16←もう聖霊きてる
・荒野で40日間聖霊によって導かれた。（いたるところに聖霊はいた。ペンテコステの前にも）
・旧約聖書「神の霊」という言い回しでサムソンやダビデにたしかに降ってる。
・創世記でアダムを作られたときの「命の息」は聖霊。天地創造の最初から、その存在は暗喩されていた。
 
・はっきりとした線引きは難しいけど、ペンテコステ以降は「異邦人」にも降るようになった。それまではイスラエル（ユダヤ）の民におもに降っていた。（旧約聖書でも、異邦人にも聖霊はたらいている記述はある。非常にデリケートなところではある。おおまかな線引きは、そういうこと）
 
・油注ぎ（王になる前の儀式）→聖霊が下される儀式
・旧約聖書のこの時代だと、油は貴重。それをあたまにそぐ、ということでは現代では意味合いが違う。
