### ISSUE TITLE
制作にあたって勇気を頂いたので直接お礼を伝えたい方々一覧

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#67]
・上馬キリスト教会中の人

・あやメディアーあやめさん

・脚本家Sさん←コンタクト済み
・メンヘラ.jpーわかり手さん（勇気を頂いたと言うか、メンヘラ.jp のモデルを参考にしたい部分があるのでお話し聞きたい）←方向性が違うと感じたため、いつかみではコンタクトなし

**Comment by uesakaeita** [comment]
**脚本家Sさんへのコンタクト**
12月中に、栄太がFBメッセンジャーで連絡します。

文章は栄太が概要を作りますので、見てもらっていいでしょうか？

**Comment by kasugamori** [comment]
「文章は栄太が概要を作りますので、見てもらっていいでしょうか？」→了解です。お願いします。

**Comment by uesakaeita** [comment]
脚本家Sさんからの返事は直接見せたとおりです。

ほかの方への連絡はお願いします。

**Comment by uesakaeita** [comment]
全記事の修正が終わったので、再度確認したいと思います。

かすがさんのほうで連絡したい方、まだ連絡していない方はいますか？

再度、リストアップをお願いします。

**Comment by kasugamori** [comment]
・上馬キリスト教会中の人
・あやメディアーあやめさん
