### ISSUE TITLE
5話　ハガレン　監修チェック中

### ISSUE THREAD

**Issue by uesakaeita** [lampmate/itukami#68]
（下記は骨子issueから　かすがさんのコメントの転記です）

今週石川先生にサポートしてもらいたいので、次回作もぼちぼち書き始めます。

また、12/1の映画公開に間に合わせたいです。

ーーーーーーーーーー

【鋼の錬金術師】
・キャラクターの魅力

欠点が必ずある
エドマスタング
→罪を認めている人間の魅力

・ウィンリィの両親は隣人愛の実践者
しかし物語の構成上 死ななくてはならない

・等価交換の法則は世界の法則として描かれるし、読み手もそこに納得するから厚みのある物語として受け入れられた。最終的に主人公が選ぶのは、等価交換を超えた「愛」とも呼べる選択肢である。

ーーーイエスの十字架は等価交換を超える「与える愛」を尊いと感じるならば、キリスト教のことを知ればそこに何か思うところができるはず。

**Comment by kasugamori** [comment]
ハガレンはまだクロージング挿入していません（マンガアプリか聖書への誘導）
→完了してます。

**Comment by kasugamori** [comment]
ハガレンコラム骨子
![img_3371](https://user-images.githubusercontent.com/33079296/35851275-df30bad0-0b6a-11e8-9c45-57dfa0f04de1.JPG)

**Comment by uesakaeita** [comment]
骨子ありがとうございます！

ただ、申し訳ありません。。。
現状の写真添付では文字が横向きで読みにくいため、縦向きの写真で、２枚分割して添付していただけませんでしょうか。

骨子さっそく読んでみようとしたのですが、、、
お手数おかけします。もし、かすがさんの方で出来なければ、私がやりますので、そのようにコメントください。

よろしくお願いします。

**Comment by kasugamori** [comment]
もうコラムがほぼ書き終わっているのでそちらを観てください。ワードプレスにあがってます。
