### ISSUE TITLE
各話「ネタバレの注意書き」に、SNSリンク添付

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#69]

**Comment by uesakaeita** [comment]
この記事はネタバレを含んでいます。ネタバレが嫌な方は、原作を読んでからまた遊びに来て下さい！更新のお知らせを受け取りたい方は、TwitterフォローかFacebookページにいいね！をお願いします！

-----------------------

この文章の　「Twitterフォロー　Facebookページ」　にリンクを付ければいいですか？

**Comment by kasugamori** [comment]
はい。
