### ISSUE TITLE
タイトル案のアンケート

### ISSUE THREAD

**Issue by uesakaeita** [lampmate/itukami#7]
複数人にアンケートを取り、タイトルを決めたい。

**Comment by uesakaeita** [comment]
@kasuga
これまで取ったタイトル案のアンケート履歴を知りたいです。
何人中、何人がそれぞれの案に投票したかを知りたいです。
年齢性別はとりあえず割愛しましょう。

**Comment by kasugamori** [comment]
栄太氏と私を除くと9名です。
「いつから僕らが神を知らないと〜」→6名
「いつから神を知らないと〜」→3名

**Comment by uesakaeita** [comment]
ありがとうございます。
先日の日曜日の夕方、もう1名アンケートをお願いしました。

「僕ら〜」に1票追加となりました。

アンケートを取った人は、かすがさんも見ていたかと思いますのでこの場では伏せます。

**Comment by kasugamori** [comment]
彼女も数に含めています。

**Comment by uesakaeita** [comment]
私が17時頃にアンケートしてもらった方は男性の方、dさんです！
なので、想定している方と違うかもしれません。

**Comment by kasugamori** [comment]
理解しました。では栄太さんと私を除いて計10名です。
内訳は
「いつから僕らが神を知らないと〜」→7名
「いつから神を知らないと〜」→3名
という結果です。

**Comment by kasugamori** [comment]
タイトルは「いつから僕らは神を知らないと錯覚していた？」といたします。
