### ISSUE TITLE
各話の冒頭に「キャラ紹介」「あらすじ」・場面ごとの「状況説明」挿入

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#72]
・キャラ紹介はバナーを作る
・あらすじは定型句を
・場面毎の状況説明は、見直しながら挿入

**Comment by uesakaeita** [comment]
案のスクショを添付します


## A案：もともとの、、文字を挿入したのみ
![image](https://user-images.githubusercontent.com/33074227/33656358-28c57f7e-dab9-11e7-8765-9562e5d59f32.png)

## B案
![image](https://user-images.githubusercontent.com/33074227/33656411-4d24f994-dab9-11e7-96d8-542a509d91dd.png)

プラグイン経由で装飾しました。
テンプレートに入れてあります。

もちろんテンプレートの修正もできます。


とりあえずB案の自己紹介を、各記事の最初に挿入するのはどうでしょうか。
各記事の修正は3分でできると思います。

**Comment by uesakaeita** [comment]
各記事の冒頭に、

・登場人物紹介
・あらすじ
・場面説明

をどう挿入するかですが、
記事の冒頭に登場人物紹介があり

その人物紹介の流れであらすじを説明し、紹介は閉じられたあとの
会話文の前に、場面説明を挿入する、

という案はいかがでしょうか？

それか、まとめちゃってもいいのか……

**Comment by uesakaeita** [comment]
口頭で返事をいただきました。

冒頭に、人物紹介、あらすじ、場面説明を一まとめとし、
プラグインのボックスタイプで進めましょう。

closeします。
