### ISSUE TITLE
アイキャッチ画像の規格決める

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#79]
・アイキャッチ画像の規格決める
・過去のものを修正していく
・利用できるところも考える

**Comment by uesakaeita** [comment]
デザインの全体がまとまってきたので、
アイキャッチ規格についても整えていきたいと思います。
私がいくつか試してみて、決まりましたら連絡します。

**Comment by uesakaeita** [comment]
以下の仕様を基本ルールとしたいと考えています。

ミーティングで調整・相談よろしくお願いします。


サイズ：1200×630

文字：上に「題材タイトル（4文字程度の略称）」、中段に「×」、下に「聖書」


キャプション：2つのキャプションを入れる。メディア検索時に引っかかるようにと、見てすぐに分かるように画像埋め込みと2種類。
キャプションの内容：題材名か、タイトルか、考え中

マンガ画像の比率：3割4割程度？ミーティングで教えてください。

キャラの配置：左にマンガキャラ、右にいつかみキャラ

背景：約束の丘にするか考え中


※注意事項※
正方形で切り抜きされても大丈夫なデザインにする。フォトショップで1：1の切り抜きの確認をしてください。（ミーティングでも説明します）

**Comment by uesakaeita** [comment]
## 3月10日ミーティングにて

画像サイズなど、承諾をいただきました。

次回にアイキャッチを作るときに、一緒に作りましょう。説明します。

クローズします。
