### ISSUE TITLE
第7話　るろうに剣心

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#80]

**Comment by kasugamori** [comment]
![img_2704](https://user-images.githubusercontent.com/33079296/33586747-37c745d6-d9ae-11e7-900f-40884efdc2d7.JPG)

**Comment by uesakaeita** [comment]
なるほどなるほど！とても楽しく読ませてもらいました。

改めて見てみると、るろ剣は「ログライン」がしっかり成立している作品なんだなと思いました。


るろ剣が贖罪の物語だとした場合、
結末に「救い」となるようなシーン、エンディングはありましたっけ？

ラストをよく覚えてません。
というか、何編まで見たかよく覚えてないから読みに行かなきゃだな。

剣心と似て非なる存在、キャラクターはいましたか？
剣心は自分の罪に向き合い、贖罪という道を選んだ。
一方で、自分の罪に向き合い、別の道を選んだ、といった好敵手的な存在がいるのであれば、
より剣心の姿勢が浮き彫りになってくる…のだろうかと思いました。



他のマンガでも「贖罪」をテーマにしているものがあるように思うので、
とても面白い切り口で、他のマンガとの比較もできるそうで面白そうだと思いました。

敵を殺してヤッターのくだりはよく分かりませんでした。

**Comment by kasugamori** [comment]
・るろ剣のなかの大きな悪役は「悪を肯定して(自分の矜持で行う)いる存在」(志々雄真実、ウドウジンエ、斎藤一)
・るろ剣の特徴ーテーマは繰り返されている。主人公の成長物語ではなく、あくまで「贖罪」の物語
・剣心は、自分の罪の赦しを自分でできない。周りはそれを勧めがち。自分で自分の罪を許すことをしてしまったら読者もついていかない。

**Comment by kasugamori** [comment]
（石川先生監修）
（１）剣心は、いわゆる「求道者である」ともいえるのでは。「私は永遠の求道者です（洗礼を受けない）」という美学もある。「自分で自分の罪を許すことができない、というのはアーメン。それを墓場までもっていくだろうひともいるだろう。「自分の罪は赦されないんだ、ということをポリシーとしている人もいる。」それも一種の傲慢であるとはクリスチャンとしては思う。（もちろん本人には言わないが）
 ・入り口としては、「永遠の求道者」でもおもしろいとは思う。（探し続けよう、と思えている時点で扉が開かれている感じがある。人間誰しも自分の価値観を壊されて、信じることは、まぁない）
→求道することの素晴らしさを伝えるに徹するのもよしなのでは。

（２）キリスト教＝勧善懲悪　という構図を払拭しようとするのはいい試みだと思います。
 
・勧善懲悪は聖書に書かれてないのか？→旧約聖書に書かれているのは勧善懲悪はまったくないかといわれると、どちらかというと書かれている。
 ・「殺さない」は十戒のなかにある。だが聖書で言われているのはあくまで「神に立ち返る」こと→罪を認めないで神にたちかえらない。
・たちかえらなければ、すぐに滅ぼされるのか？というと、最終的に救いの道を開かれている（イエス様を通して）単純な構図ではない
 
→→→だから、この話をしようとすると難しい！！！！
 
※（かすが）「いつ神」の中で語るのはやめようかな？？？？？？あくまで「聖書を読んでみてください」まででやめておくのも手かと。
 
・「殺さず」はあくまで人間的な信念。聖書の言っている「殺すな」は、神の定めた律法。（人を創られた神が殺すなといっているからであって、信念とかそういうことではない）

（３）少年漫画は「強いものが正義」というところはある。「強さがただしさ」。
 →（勝ったから剣心の宗ちゃんに伝えたメッセージが光るよね。）
 
→聖書イザヤ書「それはあなたがもっとも小さい民だからあなたを選んだ。」（優れているとか能力があるからではない）
 
→イスラエル　　エジプト・ペリシテ人・に攻められているので、「描かれている現実としては　弱肉強食」という発想になる。ただ、神様は、馬や軍備を補強することを嫌い、あくまで神に立ち返ることを喜ぶ。「剣と槍とを用いられない」第一サムエル17:47
 
・主の戦いがなんであるか、ということ。力づくではない。ダビデがゴリアテを倒すのは、主の戦いだから。

**Comment by uesakaeita** [comment]
7話、読みました。ありがとうございます。いいいいかんじ！
栄太のチェック後、30分程度のミーティング。
これからやることまとめ。


## 【かすがさんやること】
~・7話のタイトル~
~・たくみくん紹介の文章の修正~
~・あらすじの修正　教会から話が始まるため、前の話を受けて置く必要がある。~
~・るろけん画像を探す~
~・紹介アプリ　→探し中~
~・末尾のマンガ紹介文　→アプリを紹介するときにいれる~
~・たくみくんは天国ある派？、死後の世界、魂の世界あると考えている？→wikiの修正をする~
~・対抗キャラ、父母→wikiの修正をする~
~・夜空の画像~

## 【栄太やること】
~・たくみくんの紹介の画質が荒い　→栄太が修正する~
~・過去のアイキャッチ画像の場所と保存形式について　→栄太がまとめる~

~・次回予告での8話のタイトル（仮）をどうするか→タイトルのみでOK~
~・るろけん紹介の引用元リンク~
~・聖書箇所引用を会話文に入れるか→とりあえず引用で~
~・許しと赦し、漢字の統一→赦し~
~・たくみのセリフ「剣心みたいに十字架を背負いながら生き続けるって決心」の十字架をどうするか考える~

**Comment by kasugamori** [comment]
![yozora](https://user-images.githubusercontent.com/33079296/34551380-adf8b314-f15c-11e7-8ab5-a3011d26ff8a.png)
![itukamiruroken](https://user-images.githubusercontent.com/33079296/34551384-b3e72878-f15c-11e7-8fea-64c46cc1663c.png)

**Comment by kasugamori** [comment]
あらすじリンク
https://ja.wikipedia.org/wiki/るろうに剣心_-明治剣客浪漫譚-

**Comment by uesakaeita** [comment]
https://itukami.lampmate.jp/?p=998&preview=true

**Comment by kasugamori** [comment]
マンガ紹介について。るろ剣マンガ紹介は「レンタ」、及び「まんが王国」アフィリ、また紙媒体で買える方法も探し中で考えています。（いずれも申請中・探し中）

**Comment by uesakaeita** [comment]
許しと赦し、漢字の統一

**Comment by kasugamori** [comment]
マンガ紹介はアドクロップスにあった「マンガBANG!」にしています。1月31日には張り替える必要があります。このアプリはるろうに剣心は有料なので、結局はキンドルとかの紹介のほうがいいかもしれません。悩み中です。

**Comment by uesakaeita** [comment]
１月８日、記事公開。石川監修のOKをいただきました。
１月１０日、石川先生からのみことばの提案をいただきました。

修正をどうするか相談したいです。

マタイの箇所を適切の場所に追加をするか、いまあるペテロ第二の手紙のいまの聖句といれかえるか。

私は追加でいいかなぁ、場所どこがいいかなぁと思っています。
