### ISSUE TITLE
seo対策

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#87]
マンガ系を検索するときはやはり「画像検索」をすると思う。著作権違反にならないよう比率に気をつけながら「このマンガについて書いてますよ」というのがわかる画像を加工していく。１記事についき2〜3画像程度あればいいかと思う。seo対策。

**Comment by uesakaeita** [comment]
## 3月10日、ミーティングにて

PV数が1万/月　を超えたら作成することになりました。

**Comment by kasugamori** [comment]
SEO対策
「聖書　解説」で検索があったので、もう少し上位表示できるようなコンテンツを考えます。
《そのほか狙いたいワード》
・聖書　解説　わかりやすい
・聖書　解説　おすすめ
・聖書　わかりやすい本
・聖書　解説　サイト
・聖書　初心者　おすすめ
・聖書の学び方

取り掛かる時期は未定です。

**Comment by kasugamori** [comment]
SEOに影響があるのは
→良いコンテンツ　５ポイント
→被リンク　２ポイント
→コメント　１ポイント

コメントのSEOポイントは意外と高いらしいです。SEO対策はしない予定ですが、余力があればしてもいいと思っています。頭の片隅に置いておきます。

ーーーーー
一応影響がないとされてるもの
・滞在時間
・SNSのシェア数
・クリック率
ーーーーー
私のソース→https://twitter.com/hata_blog/status/986387640084717568

**Comment by kasugamori** [comment]
【内部リンク】
・適切な内部リンクはユーザーのためにもなりますし、SEO対策にもなります。10話まで公開できたら一度コンテンツを見返してみて、内部リンクを貼っていく日が必要です。
