### ISSUE TITLE
タイトル画像案

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#88]

**Comment by kasugamori** [comment]
①![itukamibig](https://user-images.githubusercontent.com/33079296/34239428-ab24aa98-e64a-11e7-9f44-52b2a8f131dc.png)
②![itukamititlelong](https://user-images.githubusercontent.com/33079296/34239429-ac6e10f6-e64a-11e7-81ae-1ac7c02a9bd6.png)
③![itukamititle](https://user-images.githubusercontent.com/33079296/34239430-adb932b0-e64a-11e7-8ad2-7241fad94d28.png)
④![itukamititle2](https://user-images.githubusercontent.com/33079296/34239432-af8d2dbc-e64a-11e7-938e-5f5f2e6219ab.png)
⑤![itukamititole](https://user-images.githubusercontent.com/33079296/34239433-b12b2af2-e64a-11e7-81ea-7002bf490160.png)

**Comment by kasugamori** [comment]
どれがいいと感じましたか？

**Comment by uesakaeita** [comment]
③番、④番、⑤番がいいと思いました。

黄色と赤の組み合あわせは警告と、らーめん二郎を意味しますが、

そういった意図でのカラーリングでしょうか…？

**Comment by uesakaeita** [comment]
失礼しました。警告色は、黄色と黒でした。

**Comment by kasugamori** [comment]
⑥
![itukamititlelast](https://user-images.githubusercontent.com/33079296/34291212-8a36aa3a-e73e-11e7-969b-ba13478e8dff.png)
修正して見ました。いかがでしょう？

**Comment by uesakaeita** [comment]
## 3月10日のミーティングにて

現在のタイトルを使うことになりました。
作っていただいたのにすみません。
クローズします。
