### ISSUE TITLE
アイキャッチ用の画像作成

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#9]

**Comment by kasugamori** [comment]
公開日が延びたので、公開までに行いたいと考えています。私が請け負います。

**Comment by uesakaeita** [comment]
はい、お願いします

**Comment by uesakaeita** [comment]
![jiken1024x684](https://user-images.githubusercontent.com/33074227/32762711-5b4cf012-c93e-11e7-8fa5-4cdcc3a73752.png)

**Comment by kasugamori** [comment]
プロローグ〜３話までのアイキャッチ全て作成してWP上アップしました。閉じます。
