### ISSUE TITLE
第8話　フルーツバスケット

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#90]
・マンガpark（アプリ）を紹介

**Comment by kasugamori** [comment]
![img_2765](https://user-images.githubusercontent.com/33079296/34432959-29ea8e68-ecbf-11e7-81e0-0ef705705d3a.PNG)

**Comment by uesakaeita** [comment]
骨子の確認OKです

**Comment by uesakaeita** [comment]
1月23日
かすがさんの下書きを確認し、修正箇所や質問について、口頭でかすがさんとチェックし合いました。

以前のようなスクショを取ってのgithub上での修正チェックは、今回はなし。

もう少し私の方で修正したらwordpressにアップします。

最終チェックの時にまたよろしくお願いします。

**Comment by uesakaeita** [comment]
かすがさんに作業をお願いしたい箇所があります。

①最後のアプリ紹介欄　parkの紹介文、リンクの作成をお願いします。

②最初のマンガ紹介欄　画像リンクの作成をお願いします。

③文中に出てくる画像挿入の画像の準備をお願いします。保留でしたら、一旦は引用文にしておきます。

④アイキャッチ画像の作成

⑤カテゴリーの設定

**Comment by kasugamori** [comment]
了解しました、とりかかります。

**Comment by kasugamori** [comment]
①〜⑤すべて完了しました。
⑥文末のクロージング、
⑦監修を受けて修正
も完了しました。確認して問題なければ公開お願いします。
⑧人物相関図
については作成中です。知っている人間しか読まないと踏んでいるので、急ぎではないと判断しました。

**Comment by uesakaeita** [comment]
了解しました！

これから確認します。

今日の20時更新できるように努めます。

フルバのアキキャッチ、なぜか見切れてますね。

アップロードしたメディアでは通常通り見えているので、サイズの都合でしょうか。

元画像はgoogleドライブにはアップしてありますか？

私の方で修正してみようと思います。

今日の記事更新に間に合うかはわかりませんが。

**Comment by uesakaeita** [comment]
質問

相関図を見ました。これはまだ修正予定？

そうまきょうくんも、透くんやゆきと同じく、ひとつ屋根の下に住んでるのでしょうか？

**Comment by kasugamori** [comment]
・フルバのアイキャッチ→見切れはワードプレスの方が原因のようでした。私はこれ以上はできないのでお願いします。ドライブに2種類アップロードしました。都合のいい方を使ってください。

・相関図→相関図通りです。完成形です（修正するとしたらもっと先、ひと段落してからの予定でした）。あの画像は数十回の試作を重ねて作り直したもので、間違った情報は入れてないです（画像の大きさや流れの都合上割愛している部分はあります）。ですが「相関図が間違っているかも」と思うのであれば、「作り手のレベルを疑われている」ということに他ならないと思います（少なくとも栄太さんはそう思っていると認識しました）。私はもともとフルバの相関図を知らない人に読んでもらえると思っていないので、不必要だと思っています。

相関図を入れると「フルバを知らない人もターゲットにしている」ということになってしまいます。それにしてしまうとあの相関図やあらすじ説明は不十分です。フルバを知らない人はそもそもターゲットではないので、相関図は入れない方がマシだと思います。

ともあれ、あの程度の相関図なら【ない方がベター】だと確信しました。消しましたので、必要だと思うなら問題意識感じる本人が作り直すなりなんなんりしてアップロードし直していただけたらと思います。素材の収集もそちらでなさってください。

**Comment by uesakaeita** [comment]
記事を発行し、石川先生にも見てもらいました。

話の中で、神義論という言葉を知りました。震災や天災についてでも。

https://kotobank.jp/word/%E7%A5%9E%E7%BE%A9%E8%AB%96-536995
