### ISSUE TITLE
「推しキャラについて語る」ようなコーナーはいかがでしょう

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#94]
アニメや漫画に改めて触れて「推しキャラへの愛情」というものがアニメや漫画への原動力となっていることを非常に感じました。

キリスト教関係なく「推しにつて語る」ようなコーナーを作るのはいかがでしょう。

**Comment by uesakaeita** [comment]
## 3月10日ミーティングにて

全体記事数の縮小により、優先順位が下がりました。
ここはクローズします。
