### ISSUE TITLE
URLからカテゴリ抜いたので、ページ内リンク全て変わっています。

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#96]
貼り直しが必要です。
現在判明しているのは
→ストーリー順に読む　　のリンク全て

**Comment by uesakaeita** [comment]
「ストーリー順によむ」のリンクを修正しました。

他を見つけたら教えてください。

**Comment by uesakaeita** [comment]
一通り戻せたと思います。closeします。
