### ISSUE TITLE
コラムの方向性・目的

### ISSUE THREAD

**Issue by kasugamori** [lampmate/itukami#99]
・コラムの方向性→未定。
・コラムの目的→SEO対策とコンテンツの充実とドメインパワーアップ

（人気作品は、グーグル検索で上位表示させることはできない。SNSには強いと思うが。ニッチなファンがいそうな作品は、タイトルにキーワードを含めて上位を狙うことも可能ではあるが。このあたりの考え方はややこしいので口頭で説明したい）

**Comment by uesakaeita** [comment]
1月19日のミーティングにて

コラムは4つのスタイルから外れていなければOKとします。

4つのスタイルについては、wikiに記載します。

issueは閉じます。

**Comment by kasugamori** [comment]
【ファイアーエムブレムde聖書】
ツイッターですでに「サウル」「リベカ」「エフライム」などの数キャラと聖書の関係人物を投稿しているのですが、これらのツイートを埋め込んでまとめたページを作るのはいかがでしょう？

FEは現在過去作のキャラクター勢揃いなソーシャルゲームが人気です。過去作のの登場人物をリアルタイムで楽しんでいる人がたくさんいますので、時季にはかなっていると思います。

ツイートを埋め込んでいくだけなので、楽といえば楽です。

方向性は「コンテンツの充実」に該当、
かつ４つのスタイルについては「よりブログ的な作り手の息抜き」に該当します。

**Comment by uesakaeita** [comment]
分かりました。
いいと思います。

sango の基本のtwitter埋め込みデザインは下記リンクをご確認ください。

他のデザインが良かったら言ってください。

https://saruwakakun.com/sango/embed-tweet
